name: Release on Tag

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'  # semver tags like v1.2.3

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up tag and version info
        id: versioning
        run: |
          echo "TAG=${GITHUB_REF_NAME}" >> "$GITHUB_ENV"
          MAJOR=$(echo "${GITHUB_REF_NAME}" | sed -E 's/^v([0-9]+).*/\1/')
          echo "MAJOR_VERSION=$MAJOR" >> "$GITHUB_ENV"
          echo "RELEASE_NAME=release-$MAJOR" >> "$GITHUB_ENV"

      - name: Template action.yaml
        run: |
          sed "s/{{TAG}}/${TAG}/g" templates/action.yaml > action.yaml

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.TAG }}
          name: ${{ env.RELEASE_NAME }}
          files: |
            README.md
            action.yaml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
